// Copyright 2022 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.

/* System headers */
#include <platform.h>

/* FreeRTOS headers */
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "timers.h"

/* Library headers */

/* App headers */
#include "app_conf.h"
#include "platform/driver_instances.h"
#include "filesystem/filesystem_demo.h"
#include "fs_support.h"

#include "ff.h"

//#pragma stackfunction 10000
 
//#define DEMO_FILEPATH		"/flash/fs/demo1.txt"
//#define DEMO_FILEPATH		"/flash/firmware/deen.txt"

//#define DEMO_FILEPATH		"/flash/firmware/DEEN.TXT"
#define DEMO_FILEPATH1		"/flash/fs/W25X101.PDF"
#define DEMO_FILEPATH4		"/flash/fs/W25X104.PDF"
#define DEMO_FILEPATH6		"/flash/fs/W25X106.pdf"
#define DEMO_FILEPATH10		"/flash/fs/W25X1010.pdf"
#define DEMO_FILEPATH11		"/flash/fs/W25X1011.pdf"
#define DEMO_FILEPATH		"/flash/fs/DEMO.TXT"
	FRESULT fr;     /* Return value */
    DIR dj;         /* Directory object */
    FILINFO fno;    /* File information */

SemaphoreHandle_t xMutex = NULL;
FRESULT scan_files (
    char* path        /* Start node to be scanned (***also used as work area***) */
);
 // A task that creates a mutex.
void vATask( void * pvParameters )
 {
    // Create the mutex to guard a shared resource.
    xMutex = xSemaphoreCreateRecursiveMutex();
 }

#pragma stackfunction 1000
FRESULT scan_files (
    char* path        /* Start node to be scanned (***also used as work area***) */
)
{
    FRESULT res;
    DIR dir;
    UINT i;
    static FILINFO fno;


    res = f_opendir(&dir, path);                       /* Open the directory */
    if (res == FR_OK) {
        for (;;) {
            res = f_readdir(&dir, &fno);                   /* Read a directory item */
            if (res != FR_OK || fno.fname[0] == 0) break;  /* Break on error or end of dir */
            if (fno.fattrib & AM_DIR) {                    /* It is a directory */
                i = strlen(path);
                sprintf(&path[i], "/%s", fno.fname);
                res = scan_files(path);                    /* Enter the directory */
                if (res != FR_OK) break;
                path[i] = 0;
            } else {                                       /* It is a file. */
                printf("%s/%s\n", path, fno.fname);
            }
        }
        f_closedir(&dir);
    }

    return res;
}
	
void sl_wfx_app_fw_size(int value)
{
#if 0 
	//////////////////////////////////////////////
    if( xMutex != NULL )
    {
        // See if we can obtain the mutex.  If the mutex is not available
        // wait 10 ticks to see if it becomes free.    
        if( xSemaphoreTakeRecursive( xMutex, ( TickType_t ) 10 ) == pdTRUE )
        {
            // We were able to obtain the mutex and can now access the
            // shared resource.
			
    //FRESULT fr;     /* Return value */
    //DIR dj;         /* Directory search object */
    //FILINFO fno;    /* File information */
	
	rtos_printf("_USE_LFN = %d , _USE_FIND =%d\n", FF_USE_LFN , FF_USE_FIND);
#if FF_USE_LFN
    char lfn[_MAX_LFN + 1];
    fno.lfname = lfn;
    fno.lfsize = sizeof lfn;
#endif

#if FF_USE_FIND
    fr = f_findfirst(&dj, &fno, "", "dsc*.jpg");  /* Start to search for JPEG files with the name started by "dsc" */
#endif
    while (fr == FR_OK && fno.fname[0]) {         /* Repeat while an item is found */
#if FF_USE_LFN
        printf("%-12s  %s\n", fno.fname, fno.lfname);/* Display the item name */
#else
        printf("%s\n", fno.fname);
#endif
#if FF_USE_FIND
        fr = f_findnext(&dj, &fno);               /* Search for next item */
#endif

    }
    f_closedir(&dj);
	
            // ...
            // For some reason due to the nature of the code further calls to 
            // xSemaphoreTakeRecursive() are made on the same mutex.  In real
            // code these would not be just sequential calls as this would make
            // no sense.  Instead the calls are likely to be buried inside
            // a more complex call structure.
            xSemaphoreTakeRecursive( xMutex, ( TickType_t ) 10 );
            xSemaphoreTakeRecursive( xMutex, ( TickType_t ) 10 );

            // The mutex has now been 'taken' three times, so will not be 
            // available to another task until it has also been given back
            // three times.  Again it is unlikely that real code would have
            // these calls sequentially, but instead buried in a more complex
            // call structure.  This is just for illustrative purposes.
            xSemaphoreGiveRecursive( xMutex );
            xSemaphoreGiveRecursive( xMutex );
            xSemaphoreGiveRecursive( xMutex );

            // Now the mutex can be taken by other tasks.
        }
        else
        {
            // We could not obtain the mutex and can therefore not access
            // the shared resource safely.
        }
    }
#endif	

#if 1	
///////////////////////////////////////////////////////////////////
#if 0
	vTaskDelay(pdMS_TO_TICKS(1000));
    char str[12];

    /* Get volume label of the default drive */
    f_getlabel("", str, 0);
	printf("1111f_getlabel=%s\n", str); 
    /* Get volume label of the drive 2 */
    f_getlabel("2:", str, 0);
	printf("2222f_getlabel=%s\n", str); 
#endif
///////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////
#if 0
    FATFS *fs;
    DWORD fre_clust, fre_sect, tot_sect;
    FRESULT res;

    /* Get volume information and free clusters of drive 1 */
    res = f_getfree("1:", &fre_clust, &fs);
    //if (res) die(res);
	
    /* Get total sectors and free sectors */
    tot_sect = (fs->n_fatent - 2) * fs->csize;
    fre_sect = fre_clust * fs->csize;

    /* Print the free space (assuming 512 bytes/sector) */
    printf("%10lu KiB total drive space.\n%10lu KiB available.\n", tot_sect / 2, fre_sect / 2);
#endif
////////////////////////////////////////////////////////////////////	
    FATFS fs;
	FRESULT res;
    char buff[256];

	printf("FIRST \n", 0);
    res = f_mount(&fs, "", 0);
    if (res == FR_OK) {
        strcpy(buff, "/");
        res = scan_files(buff);
    }
	
#if 0	
	vTaskDelay(pdMS_TO_TICKS(1000));
	
	printf("SECOND \n", 0);	
    res = FR_OK;//f_mount(&fs, "/flash/firmware", 0);
    if (res == FR_OK) {
        strcpy(buff, "/");
        res = scan_files(buff);
    }
	vTaskDelay(pdMS_TO_TICKS(1000));
	
	printf("THIRD \n", 0); 
    res = FR_OK;//f_mount(&fs, "", 0);
    if (res == FR_OK) {
        strcpy(buff, "/");
        res = scan_files(buff);
    }
	vTaskDelay(pdMS_TO_TICKS(1000));
#endif	
#if 0
			//taskENTER_CRITICAL();
			//xSemaphoreTakeRecursive();	
			fr = f_findfirst(&dj, &fno, "/xcore_fs/firmware", "*.*"); /* Start to search for photo files */

			while (fr == FR_OK && fno.fname[0]) {         /* Repeat while an item is found */
				printf("%s\n", fno.fname);                /* Print the object name */
				fr = f_findnext(&dj, &fno);               /* Search for next item */
			}
			printf("%d\n", fr); 
			printf("%s\n", fno.fname); 
			//xSemaphoreGiveRecursive() ;
			//taskEXIT_CRITICAL();
			f_closedir(&dj);
			
						//taskENTER_CRITICAL();
			//xSemaphoreTakeRecursive();	
			fr = f_findfirst(&dj, &fno, "/xcore_fs/flash/firmware", "*.*"); /* Start to search for photo files */

			while (fr == FR_OK && fno.fname[0]) {         /* Repeat while an item is found */
				printf("%s\n", fno.fname);                /* Print the object name */
				fr = f_findnext(&dj, &fno);               /* Search for next item */
			}
			printf("%d\n", fr); 
			printf("%s\n", fno.fname); 
			//xSemaphoreGiveRecursive() ;
			//taskEXIT_CRITICAL();
			f_closedir(&dj);
#endif
#if 0
			vTaskDelay(pdMS_TO_TICKS(1000));
			//taskENTER_CRITICAL();
			//xSemaphoreTakeRecursive();	
			fr = f_findfirst(&dj, &fno, "/FLASH/FIRMWARE/", "*.*"); /* Start to search for photo files */

			while (fr == FR_OK && fno.fname[0]) {         /* Repeat while an item is found */
				printf("%s\n", fno.fname);                /* Print the object name */
				fr = f_findnext(&dj, &fno);               /* Search for next item */
			}
			printf("%d\n", fr); 
			printf("%s\n", fno.fname); 
			//xSemaphoreGiveRecursive() ;
			//taskEXIT_CRITICAL();
			f_closedir(&dj);
			
			
			vTaskDelay(pdMS_TO_TICKS(1000));
			//taskENTER_CRITICAL();
			//xSemaphoreTakeRecursive();	
			fr = f_findfirst(&dj, &fno, "/flash/firmware/", "*.*"); /* Start to search for photo files */

			while (fr == FR_OK && fno.fname[0]) {         /* Repeat while an item is found */
				printf("%s\n", fno.fname);                /* Print the object name */
				fr = f_findnext(&dj, &fno);               /* Search for next item */
			}
			printf("%d\n", fr); 
			printf("%s\n", fno.fname); 
			//xSemaphoreGiveRecursive() ;
			//taskEXIT_CRITICAL();
			f_closedir(&dj);

			vTaskDelay(pdMS_TO_TICKS(1000));
			//taskENTER_CRITICAL();
			//xSemaphoreTakeRecursive();	
			fr = f_findfirst(&dj, &fno, "/FIRMWARE", "*.*"); /* Start to search for photo files */

			while (fr == FR_OK && fno.fname[0]) {         /* Repeat while an item is found */
				printf("%s\n", fno.fname);                /* Print the object name */
				fr = f_findnext(&dj, &fno);               /* Search for next item */
			}
			printf("%d\n", fr); 
			printf("%s\n", fno.fname); 
			//xSemaphoreGiveRecursive() ;
			//taskEXIT_CRITICAL();
			f_closedir(&dj);
			
			
			vTaskDelay(pdMS_TO_TICKS(1000));
#endif	
#if 1		
			//taskENTER_CRITICAL();
			//xSemaphoreTakeRecursive();
			rtos_printf("TILE = %d\n", 0);			
			fr = f_findfirst(&dj, &fno, "/flash/fs", "*.*"); /* Start to search for photo files */

			while (fr == FR_OK && fno.fname[0]) {         /* Repeat while an item is found */
				printf("TILE0_fno.fname = %s\n", fno.fname);                /* Print the object name */
				fr = f_findnext(&dj, &fno);               /* Search for next item */
			}
			printf("TILE0_last fr = %d\n", fr); 
			printf("TILE0_last fno.fname = %s\n", fno.fname); 
			//xSemaphoreGiveRecursive() ;
			//taskEXIT_CRITICAL();
			f_closedir(&dj);	
#endif			
#endif
	/////////////////////////////////////////////	
	/*******************FILE CREATE***/

    FIL fil;        /* File object */
    //char line[100] = "HELLO WORLD NEWELY CREATED"; /* Line buffer */
#if 0
char line[20000] = "HOW ARE YOU WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  HELLO WORLD NEWELY CREATE\
				  NEWLY ADDED FOR TESTINGGG";	
#endif
    char line1[100] = "FOR TESTING NEW FILE THIS DATA BEING ADDED"; /* Line buffer */
	//FRESULT fr;     /* FatFs return code */
	UINT br, bw;         /* File read/write count */
	br = 20000;
	char filename[200];
#if 1		
	//sprintf(filename, "/flash/firmware/message%d.txt", value);
	sprintf(filename, "/flash/fs/mess%d.txt", value);
	
	rtos_printf("file name = %s\n", filename);
	
	fr = f_open(&fil, (const TCHAR *)filename, FA_OPEN_APPEND | FA_CREATE_NEW | FA_WRITE);
	
	//fr = f_open(&fil, "/flash/firmware/message1.txt", FA_CREATE_NEW | FA_WRITE);
	
	rtos_printf("fr = f_open(&fil, %d)\n", fr);
	
	//if(value == 250)
		fr = f_write(&fil, line1, 100, &bw);           /* Write it to the destination file */
	//else
		//fr = f_write(&fil, line, 100, &bw);           /* Write it to the destination file */
	
	rtos_printf("fr = f_write(&fil, %d)\n", fr);
	
	f_close(&fil);
#endif	
	//////////////////////////////////////////////	

}

static void filesystem_demo(void* args)
{
    FIL test_file;
    FRESULT result;
    uint32_t demo_file_size = -1;
    uint32_t bytes_read = 0;
    uint8_t *file_contents_buf = NULL;



/////////////DIRECTORY SEARCH////////////////////////
    FATFS fs;
    FRESULT res;
    char buff[256];


    //res = f_mount(&fs, "", 1);
    //if (res == FR_OK) 
    {
        strcpy(buff, "/");
        res = scan_files(buff);
    }
/////////////////////////////////////////////////////
    
////////////////FILE SEARCH//////////////////////////
    FRESULT fr;     /* Return value */
    DIR dj;         /* Directory object */
    FILINFO fno;    /* File information */

    fr = f_findfirst(&dj, &fno, "", "*.*"); /* Start to search for photo files */

    while (fr == FR_OK && fno.fname[0]) {         /* Repeat while an item is found */
        printf("%s\n", fno.fname);                /* Print the object name */
        fr = f_findnext(&dj, &fno);               /* Search for next item */
    }
    //Debug_Output2(0,"File close %d , %s\n", fr,fno.fname);
    f_closedir(&dj);
//////////////////////////////////////////////////////


///////////////////TXT ADDING ////////////////////////
	/*******************FILE CREATE***/
   	FIL fil;        /* File object */
    	char line1[100] = "FOR TESTING NEW FILE THIS DATA BEING ADDED"; /* Line buffer */
	UINT bw;         /* File read/write count */
	char filename[200];
	
	//sprintf(filename, "IMG_FL_8042_32092_20220101_100000_08.jpeg");
	
	//rtos_printf("file delete status = %d\n", f_unlink(filename));
#if 0		
//IMG_FL_8042_32092_20220101_100000_00.jpeg
	//sprintf(filename, "IMG_FL_8042_32092_20220101_100000_08.jpeg");
	
	sprintf(filename, "/flash/fs/mess%d.txt", 1);
	
	rtos_printf("file name = %s\n", filename);
	
	fr = f_open(&fil, (const TCHAR *)filename, FA_CREATE_NEW | FA_WRITE | FA_READ);
	
	rtos_printf("fr = f_open(&fil, %d)\n", fr);
	
	fr = f_write(&fil, line1, 100, &bw);           /* Write it to the destination file */
	
	rtos_printf("fr = f_write(&fil, %d)\n", fr);
	
	f_close(&fil);
#endif	
//////////////////////////////////////////////    

//////////////////////////////////////////
    //FATFS fs;
	//FRESULT res;
    //char buff[256];

	printf("FIRST \n", 0);
    //res = f_mount(&fs, "", 0);
    //if (res == FR_OK) 
    {
        strcpy(buff, "/");
        res = scan_files(buff);
    }
//////////////////////////////////////////
	int i = 0;
	
	//char filename[100];
		
	/*for(i=0;i<3;i++)
	{
		sprintf(filename, "/firmware/mess%d.txt", i);
		rtos_printf("file delete status = %d\n", f_unlink(filename));
	}*/
		
	//rtos_printf("file delete status = %d\n", f_unlink(DEMO_FILEPATH));
#if 0	
	rtos_printf("filesystem_demo 1 %s\n", DEMO_FILEPATH1);
    result = f_open(&test_file, DEMO_FILEPATH1, FA_READ);
    if (result == FR_OK)
    {
        rtos_printf("Found file 1 %s\n", DEMO_FILEPATH1);
        demo_file_size = f_size(&test_file);
		rtos_printf("demo_file_size 1 = %ld\n", demo_file_size);
	}

	rtos_printf("filesystem_demo %s\n", DEMO_FILEPATH);
    result = f_open(&test_file, DEMO_FILEPATH, FA_READ);
    if (result == FR_OK)
    {
        rtos_printf("Found file %s\n", DEMO_FILEPATH);
        demo_file_size = f_size(&test_file);
		rtos_printf("demo_file_size  = %ld\n", demo_file_size);
	}

	rtos_printf("filesystem_demo 6 %s\n", DEMO_FILEPATH6);
    result = f_open(&test_file, DEMO_FILEPATH6, FA_READ);
    if (result == FR_OK)
    {
        rtos_printf("Found file 6 %s\n", DEMO_FILEPATH6);
        demo_file_size = f_size(&test_file);
		rtos_printf("demo_file_size 6 = %ld\n", demo_file_size);
	}

	rtos_printf("filesystem_demo 11 %s\n", DEMO_FILEPATH11);
    result = f_open(&test_file, DEMO_FILEPATH11, FA_READ);
    if (result == FR_OK)
    {
        rtos_printf("Found file 11 %s\n", DEMO_FILEPATH11);
        demo_file_size = f_size(&test_file);
		rtos_printf("demo_file_size 11 = %ld\n", demo_file_size);
	}

	rtos_printf("filesystem_demo 10 %s\n", DEMO_FILEPATH10);
    result = f_open(&test_file, DEMO_FILEPATH10, FA_READ);
    if (result == FR_OK)
    {
        rtos_printf("Found file 10 %s\n", DEMO_FILEPATH10);
        demo_file_size = f_size(&test_file);
		rtos_printf("demo_file_size 10 = %ld\n", demo_file_size);
	}
	
	rtos_printf("filesystem_demo 4 %s\n", DEMO_FILEPATH4);
    result = f_open(&test_file, DEMO_FILEPATH4, FA_READ);
    if (result == FR_OK)
    {
        rtos_printf("Found file 4 %s\n", DEMO_FILEPATH4);
        demo_file_size = f_size(&test_file);
		rtos_printf("demo_file_size 4 = %ld\n", demo_file_size);
	}
#endif	
	rtos_printf("filesystem_demo %s\n", DEMO_FILEPATH);
    result = f_open(&test_file, DEMO_FILEPATH, FA_READ);
    if (result == FR_OK)
    {
        rtos_printf("Found file %s\n", DEMO_FILEPATH);
        demo_file_size = f_size(&test_file);
		rtos_printf("demo_file_size %ld\n", demo_file_size);
        file_contents_buf = pvPortMalloc(sizeof(uint8_t)*demo_file_size);
        configASSERT(file_contents_buf != NULL);

        result = f_read(&test_file,
                        (uint8_t*)file_contents_buf,
                        demo_file_size,
                        (unsigned int*)&bytes_read);
        configASSERT(bytes_read == demo_file_size);
    } else {
        rtos_printf("Failed to open file %s\n", DEMO_FILEPATH);
    }
    if (demo_file_size != -1)
    {
        rtos_printf("Loaded file %s\n", DEMO_FILEPATH);
        f_close(&test_file);
    }

    while(1)
    {
#if 1		
			//taskENTER_CRITICAL();
			//xSemaphoreTakeRecursive();
			rtos_printf("TILE = %d\n", 0);			
			fr = f_findfirst(&dj, &fno, "", "*.*"); /* Start to search for photo files */

			while (fr == FR_OK && fno.fname[0]) {         /* Repeat while an item is found */
				printf("TILE0_fno.fname = %s\n", fno.fname);                /* Print the object name */
				fr = f_findnext(&dj, &fno);               /* Search for next item */
			}
			printf("TILE0_last fr = %d\n", fr); 
			printf("TILE0_last fno.fname = %s\n", fno.fname); 
			//xSemaphoreGiveRecursive() ;
			//taskEXIT_CRITICAL();
			f_closedir(&dj);	
#endif				
        if (demo_file_size != -1)rtos_printf("Contents of %s are:\n%s\n", DEMO_FILEPATH, file_contents_buf);
		else rtos_printf("No file found in location = %s \n", DEMO_FILEPATH);
        vTaskDelay(pdMS_TO_TICKS(5000));
    }
}

void filesystem_demo_create( UBaseType_t priority )
{
    xTaskCreate((TaskFunction_t) filesystem_demo,
                "filesystem_demo",
                RTOS_THREAD_STACK_SIZE(filesystem_demo),
                NULL,
                priority,
                NULL);
}
